# Servicios
services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/data

  gymi_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo
# Volúmenes
volumes:
  mongo-data:
    driver: local